export const BREED_SEARCH = 'BREED_SEARCH';
export const COUNTRY_FILTER = 'COUNTRY_FILTER';
export const CITY_FILTER = 'CITY_FILTER';
export const PRICE_FROM_FILTER = 'PRICE_FROM_FILTER';
export const PRICE_TO_FILTER = 'PRICE_TO_FILTER';
export const SORT_FILTER = 'SORT_FILTER';
