export interface Ad {
    _id: string,
    title: string,
    description: string,
    city: string,
    country: string,
    date: Date,
    picture: string,
    sellerID: string,
    status: string,
    price: number,
    docID?: string,
    saleDate?: Date,
    closingDate?: Date,
}
