import pic1 from './pictures/1.jpeg';
import pic2 from './pictures/2.jpg';
import pic3 from './pictures/3.jpg'
import pic4 from './pictures/4.jpeg'

const adsData = [
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Brest',
        country: 'Belarus',
        price: '3000',
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Bulldog',
        city: 'Paris',
        country: 'France',
        price: '100',
        date: new Date(2021, 6,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic2,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'New York',
        country: 'USA',
        price: '200',
        date: new Date(2021, 7,20, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic3,
    },
    {
        id: 1,
        title: 'Akita Chow',
        city: 'Minsk',
        country: 'Belarus',
        price: '340',
        date: new Date(2021, 7,15, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic4,
    },
    {
        id: 1,
        title: 'Xolo',
        city: 'Warsaw',
        country: 'Poland',
        price: '350',
        date: new Date(2021, 6,5, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Xolo',
        city: 'Moscow',
        country: 'Russia',
        price: '340',
        date: new Date(2021, 5,25, 17,35),
        sellerID: 1,
        description: 'big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: '310',
        date: new Date(2021, 6,27, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic2,
    },
    {
        id: 1,
        title: 'Beagle',
        city: 'Minsk',
        country: 'Belarus',
        price: '300',
        date: new Date(2021, 5,17, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic3,
    },
    {
        id: 1,
        title: 'Bichon Frise',
        city: 'Novopolotsk',
        country: 'Belarus',
        price: '300',
        date: new Date(2021, 7,2, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic4,
    },
    {
        id: 1,
        title: 'Borsoi',
        city: 'Brest',
        country: 'France',
        price: '300',
        date: new Date(2021, 7,5, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Borsoi',
        city: 'Gdansk',
        country: 'Poland',
        price: '400',
        date: new Date(2021, 8,5, 17,35),
        sellerID: 1,
        description: 'big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Dalmatin',
        city: 'Berlin',
        country: 'Germany',
        price: '2780',
        date: new Date(2021, 8,2, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic2,
    },
    {
        id: 1,
        title: 'Dalmatin',
        city: 'Berlin',
        country: 'Germany',
        price: '900',
        date: new Date(2021, 6,10, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic3,
    },
    {
        id: 1,
        title: 'Huskita',
        city: 'Madrid',
        country: 'Spain',
        price: '3600',
        date: new Date(2021, 7,25, 17,40),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic4,
    },
    {
        id: 1,
        title: 'Irish Terrier',
        city: 'Gomel',
        country: 'Belarus',
        price: '300',
        date: new Date(2021, 7,25, 18,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Maltese',
        city: 'Gomel',
        country: 'Belarus',
        price: '300',
        date: new Date(2021, 5,5, 17,35),
        sellerID: 1,
        description: 'Потрясающий любящий мальчик, здорововый, привитый',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Xolo',
        city: 'Moscow',
        country: 'Russia',
        price: '2000',
        date: new Date(2021, 5,20, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic2,
    },
    {
        id: 1,
        title: 'Corgi',
        city: 'Warsaw',
        country: 'Poland',
        price: '300',
        date: new Date(2021, 6,4, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic3,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Riga',
        country: 'Latvia',
        price: '300',
        date: new Date(2021, 7,1, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic4,
    },
    {
        id: 1,
        title: 'Poodle',
        city: 'Nice',
        country: 'France',
        price: '300',
        date: new Date(2021, 7,11, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic1,
    },
]

export { adsData };