import pic1 from './pictures/1.jpeg';
import pic2 from './pictures/2.jpg';
import pic3 from './pictures/3.jpg'
import pic4 from './pictures/4.jpeg'

const adsData = [
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic2,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic3,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic4,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic2,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic3,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic4,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description big description',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic2,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic3,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic4,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'Потрясающий любящий мальчик, здорововый, привитый',
        picture: pic1,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic2,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic3,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic4,
    },
    {
        id: 1,
        title: 'Yorkshire Terrier',
        city: 'Minsk',
        country: 'Belarus',
        price: 300,
        date: new Date(2021, 7,25, 17,35),
        sellerID: 1,
        description: 'The best puppy!',
        picture: pic1,
    },
]

export { adsData };